version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_food
    restart: always
    environment:
      POSTGRES_DB: food_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
